# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171127_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teac%m', verbose_name='\u5934\u50cf'),
        ),
    ]
