# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='course',
        ),
    ]
