# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171129_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
