# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/image/default.png', upload_to='image/%Y/%m'),
        ),
    ]
