# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='send_typr',
            new_name='send_type',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birday',
            new_name='birthday',
        ),
    ]
